//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace web_odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users1
    {
        [Required(ErrorMessage = "{0} alani bos birakilamaz."),
            EmailAddress(ErrorMessage ="{0} alani icin gecerli bir E-posta adresi giriniz. ")]
        public string userEmail { get; set; }

        [Required(ErrorMessage = "{0} alani bos birakilamaz.")]
        public string userPassword { get; set; }
    }
}
