//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace web_odev3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum1
    {
        public int YorumID { get; set; }
        public string Yorum_satiri { get; set; }
        public Nullable<int> HaberID { get; set; }
    
        public virtual Haber Haber { get; set; }
    }
}
